<template>
  <div
    :class="['toast', showClass]"
  >
    <div class="container-icon">
      <icon-close
        @click="hideToast"
        class="icon"
      />
    </div>
    <p
      v-for="(text, i) in messages"
      :key="i"
    >
     {{ text }}
    </p>
  </div>
</template>

<script lang="ts" setup>
import IconClose from "@/components/icons/IconClose.vue"
import { useToastStore } from "@/stores/toast"
import { computed } from "@vue/reactivity"
import { storeToRefs } from "pinia"

const toastStore = useToastStore()
const hideToast = toastStore.hideToast

const { show, messages } = storeToRefs(toastStore)

const showClass = computed(() => show.value ? 'show' : '')
</script>

<style lang="scss" scoped>
.toast {
  position: absolute;
  max-width: 360px;
  top: 20px;
  right: 20px;
  padding: 0px 12px;
  border-radius: 8px;
  background: #2d3436;
  color: #FFFFFF;
  opacity: 0;
  transition: opacity 0.3s;

  &.show {
    opacity: 1;
    animation: bounce-in-right 1.1s both;
  }

  .container-icon {
    display: flex;
    padding-top: 8px;
    fill: #4c9aff;

    .icon {
      width: 28px;
      margin-left: auto;

      &:hover {
        fill: #f9fafc;
        cursor: pointer;
      }
    }
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2022-7-29 16:26:45
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation bounce-in-right
 * ----------------------------------------
 */
@-webkit-keyframes bounce-in-right {
  0% {
    -webkit-transform: translateX(600px);
            transform: translateX(600px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    -webkit-transform: translateX(68px);
            transform: translateX(68px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  72% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  81% {
    -webkit-transform: translateX(32px);
            transform: translateX(32px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  90% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  95% {
    -webkit-transform: translateX(8px);
            transform: translateX(8px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}
</style>
